### ISSUE TITLE
Add guide for this package?

### ISSUE THREAD

**Issue by tiye** [dirk/llvm2#1]
I install llvm 3.5 via Homebrew, here's what I got when trying:

``` text
➤➤ coffee
coffee> l = require 'llvm2'
/Users/chen/repo/cirru/sepal/node_modules/llvm2/node_modules/ffi/lib/dynamic_library.js:74
    throw new Error('Dynamic Linking Error: ' + err)
          ^
Error: Dynamic Linking Error: dlopen(libLLVM-3.5.dylib, 2): image not found
  at new DynamicLibrary (/Users/chen/repo/cirru/sepal/node_modules/llvm2/node_modules/ffi/lib/dynamic_library.js:74:11)
  at Object.Library (/Users/chen/repo/cirru/sepal/node_modules/llvm2/node_modules/ffi/lib/library.js:45:12)
  at Object.<anonymous> (/Users/chen/repo/cirru/sepal/node_modules/llvm2/lib/library.js:12:19)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Users/chen/repo/cirru/sepal/node_modules/llvm2/index.js:9:16)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at repl:3:9
  at Object.exports.runInThisContext (vm.js:74:17)
  at REPLServer.replDefaults.eval (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/repl.js:46:42)
  at bound (domain.js:254:14)
  at REPLServer.runBound [as eval] (domain.js:267:12)
  at repl.js:279:12
  at REPLServer.<anonymous> (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/repl.js:79:9)
  at REPLServer.emit (events.js:129:20)
  at REPLServer.Interface._onLine (readline.js:214:10)
  at REPLServer.Interface._line (readline.js:553:8)
  at REPLServer.Interface._ttyWrite (readline.js:830:14)
  at ReadStream.onkeypress (readline.js:109:10)
  at ReadStream.emit (events.js:129:20)
  at readline.js:1175:14
  at Array.forEach (native)
  at emitKeys (readline.js:993:10)
  at ReadStream.onData (readline.js:910:14)
  at ReadStream.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:163:16)
  at ReadStream.Readable.push (_stream_readable.js:126:10)
  at TTY.onread (net.js:529:20)
```

**Comment by dirk** [comment]
@jiyinyiyong Oh nice catch! I've been busy working on this package for [Hummingbird](https://github.com/dirk/hummingbird), so it hasn't really gotten the individual attention it deserves.

I just pushed two commits: the first (18915317) adds some more feedback text if it hits a dynamic linking error at runtime, the second (b2d811da) adds some more information to the README about installation steps necessary.

**Comment by tiye** [comment]
That's helpful, thanks.
